/* 100 easter eggů — jeden na každý den výzvy, deterministicky podle dne.
   Egg = { id, min (stupeň kočky 0–5), say, m: [pohyby], fx: {g,n,top}, prop: {g,path,dur,size}, then: [pohyby po prop] }
   Pohyby (MOTIONS) animují části SVG: svg (celá), head, eyes, eyeR, tail, pawL, pawR, arms, body.
   Prop = emoji, které letí po dráze v procentech scény: path [[x,y],...] nebo speciál ('drop','laser','swat').
   Interpret je v index.html (runEgg). Nic tady nesahá na stav. */
const MOTIONS={
 wink:{t:'eyeR|eyes',k:s=>[{transform:'scaleY(1)'},{transform:`scaleY(${s})`,offset:.4},{transform:`scaleY(${s})`,offset:.7},{transform:'scaleY(1)'}],o:{duration:700}},
 blink:{t:'eyes',k:s=>[{transform:'scaleY(1)'},{transform:`scaleY(${s})`,offset:.5},{transform:'scaleY(1)'}],o:{duration:260,iterations:2}},
 sleep:{t:'eyes',k:s=>[{transform:'scaleY(1)'},{transform:`scaleY(${s})`,offset:.15},{transform:`scaleY(${s})`,offset:.85},{transform:'scaleY(1)'}],o:{duration:2600}},
 lookL:{t:'eyes',k:()=>[{transform:'translateX(0)'},{transform:'translateX(-4px)',offset:.3},{transform:'translateX(-4px)',offset:.7},{transform:'translateX(0)'}],o:{duration:1200}},
 lookR:{t:'eyes',k:()=>[{transform:'translateX(0)'},{transform:'translateX(4px)',offset:.3},{transform:'translateX(4px)',offset:.7},{transform:'translateX(0)'}],o:{duration:1200}},
 bigEyes:{t:'eyes',k:()=>[{transform:'scale(1)'},{transform:'scale(1.35)',offset:.3},{transform:'scale(1.35)',offset:.7},{transform:'scale(1)'}],o:{duration:1300}},
 purr:{t:'svg',k:()=>[{transform:'translate(0,0)'},{transform:'translate(1px,-1px)'},{transform:'translate(-1px,1px)'},{transform:'translate(0,0)'}],o:{duration:90,iterations:12}},
 jump:{t:'svg',k:()=>[{transform:'translateY(0) scale(1,1)'},{transform:'translateY(6px) scale(1.08,.9)',offset:.2},{transform:'translateY(-48px) scale(.95,1.08)',offset:.55},{transform:'translateY(0) scale(1.05,.95)',offset:.9},{transform:'translateY(0) scale(1,1)'}],o:{duration:800,easing:'cubic-bezier(.2,.8,.2,1)'}},
 hop:{t:'svg',k:()=>[{transform:'translateY(0)'},{transform:'translateY(-18px)'},{transform:'translateY(0)'}],o:{duration:320,iterations:3,easing:'ease-out'}},
 bigJump:{t:'svg',k:()=>[{transform:'translateY(0) scale(1,1)'},{transform:'translateY(10px) scale(1.12,.86)',offset:.2},{transform:'translateY(-90px) scale(.92,1.1)',offset:.55},{transform:'translateY(0) scale(1.06,.94)',offset:.92},{transform:'translateY(0)'}],o:{duration:1000,easing:'cubic-bezier(.2,.8,.2,1)'}},
 roll:{t:'svg',k:()=>[{transform:'rotate(0)'},{transform:'rotate(360deg)'}],o:{duration:900,easing:'cubic-bezier(.4,0,.2,1)'}},
 rollBack:{t:'svg',k:()=>[{transform:'rotate(0)'},{transform:'rotate(-360deg)'}],o:{duration:900,easing:'cubic-bezier(.4,0,.2,1)'}},
 backflip:{t:'svg',k:()=>[{transform:'translateY(0) rotate(0)'},{transform:'translateY(-70px) rotate(-180deg)',offset:.5},{transform:'translateY(0) rotate(-360deg)'}],o:{duration:1100,easing:'ease-in-out'}},
 tail:{t:'tail',k:()=>[{transform:'rotate(0)'},{transform:'rotate(-28deg)'},{transform:'rotate(18deg)'},{transform:'rotate(0)'}],o:{duration:450,iterations:4}},
 tailFast:{t:'tail',k:()=>[{transform:'rotate(-20deg)'},{transform:'rotate(20deg)'}],o:{duration:120,iterations:14,direction:'alternate'}},
 tailCurl:{t:'tail',k:()=>[{transform:'rotate(0)'},{transform:'rotate(-60deg)',offset:.4},{transform:'rotate(-60deg)',offset:.7},{transform:'rotate(0)'}],o:{duration:1500}},
 stretch:{t:'svg',k:()=>[{transform:'scale(1,1)'},{transform:'scale(1.06,.86)',offset:.3},{transform:'scale(.94,1.14)',offset:.7},{transform:'scale(1,1)'}],o:{duration:1300,easing:'ease-in-out'}},
 squash:{t:'svg',k:()=>[{transform:'scale(1,1)'},{transform:'scale(1.25,.7)',offset:.5},{transform:'scale(1,1)'}],o:{duration:600}},
 sneeze:{t:'head',k:()=>[{transform:'rotate(0)'},{transform:'rotate(-14deg)',offset:.45},{transform:'rotate(22deg)',offset:.6},{transform:'rotate(0)'}],o:{duration:700}},
 shake:{t:'svg',k:()=>[{transform:'rotate(0)'},{transform:'rotate(-9deg)'},{transform:'rotate(9deg)'},{transform:'rotate(-7deg)'},{transform:'rotate(7deg)'},{transform:'rotate(0)'}],o:{duration:500}},
 tiltL:{t:'head',k:()=>[{transform:'rotate(0)'},{transform:'rotate(-16deg)',offset:.3},{transform:'rotate(-16deg)',offset:.7},{transform:'rotate(0)'}],o:{duration:1400}},
 tiltR:{t:'head',k:()=>[{transform:'rotate(0)'},{transform:'rotate(16deg)',offset:.3},{transform:'rotate(16deg)',offset:.7},{transform:'rotate(0)'}],o:{duration:1400}},
 nod:{t:'head',k:()=>[{transform:'rotate(0)'},{transform:'rotate(8deg) translateY(4px)'},{transform:'rotate(0)'}],o:{duration:380,iterations:3}},
 headShake:{t:'head',k:()=>[{transform:'rotate(-10deg)'},{transform:'rotate(10deg)'}],o:{duration:220,iterations:5,direction:'alternate'}},
 headBack:{t:'head',k:()=>[{transform:'rotate(0)'},{transform:'rotate(-18deg) translateY(-6px)',offset:.3},{transform:'rotate(-18deg) translateY(-6px)',offset:.7},{transform:'rotate(0)'}],o:{duration:1600}},
 follow:{t:'head',k:()=>[{transform:'rotate(-14deg)'},{transform:'rotate(14deg)'}],o:{duration:1600,easing:'linear'}},
 followBack:{t:'head',k:()=>[{transform:'rotate(14deg)'},{transform:'rotate(-14deg)'}],o:{duration:1600,easing:'linear'}},
 waveR:{t:'pawR',k:()=>[{transform:'rotate(0) translateY(0)'},{transform:'rotate(-70deg) translateY(-14px)'},{transform:'rotate(-40deg) translateY(-14px)'},{transform:'rotate(-70deg) translateY(-14px)'},{transform:'rotate(0) translateY(0)'}],o:{duration:1100}},
 waveL:{t:'pawL',k:()=>[{transform:'rotate(0) translateY(0)'},{transform:'rotate(70deg) translateY(-14px)'},{transform:'rotate(40deg) translateY(-14px)'},{transform:'rotate(70deg) translateY(-14px)'},{transform:'rotate(0) translateY(0)'}],o:{duration:1100}},
 pawsUp:{t:'pawL,pawR',k:()=>[{transform:'translateY(0)'},{transform:'translateY(-22px)',offset:.3},{transform:'translateY(-22px)',offset:.7},{transform:'translateY(0)'}],o:{duration:1300}},
 drum:{t:'pawL,pawR',k:()=>[{transform:'translateY(0)'},{transform:'translateY(-8px)'},{transform:'translateY(0)'}],o:{duration:160,iterations:8}},
 kick:{t:'pawR',k:()=>[{transform:'translateX(0)'},{transform:'translateX(22px) rotate(-30deg)',offset:.4},{transform:'translateX(0)'}],o:{duration:600}},
 dance:{t:'svg',k:()=>[{transform:'rotate(-10deg) translateX(-10px)'},{transform:'rotate(10deg) translateX(10px)'}],o:{duration:260,iterations:6,direction:'alternate'}},
 wiggle:{t:'body',k:()=>[{transform:'rotate(-4deg)'},{transform:'rotate(4deg)'}],o:{duration:150,iterations:10,direction:'alternate'}},
 sway:{t:'svg',k:()=>[{transform:'rotate(-6deg)'},{transform:'rotate(6deg)'}],o:{duration:700,iterations:3,direction:'alternate',easing:'ease-in-out'}},
 peek:{t:'svg',k:()=>[{transform:'translateY(0)'},{transform:'translateY(170px)',offset:.3},{transform:'translateY(170px)',offset:.6},{transform:'translateY(-14px)',offset:.85},{transform:'translateY(0)'}],o:{duration:1800,easing:'ease-in-out'}},
 slideL:{t:'svg',k:()=>[{transform:'translateX(0)'},{transform:'translateX(-120px)',offset:.4},{transform:'translateX(-120px)',offset:.6},{transform:'translateX(0)'}],o:{duration:1600,easing:'ease-in-out'}},
 slideR:{t:'svg',k:()=>[{transform:'translateX(0)'},{transform:'translateX(120px)',offset:.4},{transform:'translateX(120px)',offset:.6},{transform:'translateX(0)'}],o:{duration:1600,easing:'ease-in-out'}},
 moonwalk:{t:'svg',k:()=>[{transform:'translateX(0) scaleX(-1)'},{transform:'translateX(90px) scaleX(-1)',offset:.7},{transform:'translateX(0) scaleX(1)'}],o:{duration:1800,easing:'linear'}},
 flip:{t:'svg',k:()=>[{transform:'scaleX(1)'},{transform:'scaleX(-1)',offset:.5},{transform:'scaleX(1)'}],o:{duration:1000,easing:'ease-in-out'}},
 spin:{t:'svg',k:()=>[{transform:'scaleX(1)'},{transform:'scaleX(-1)'},{transform:'scaleX(1)'},{transform:'scaleX(-1)'},{transform:'scaleX(1)'}],o:{duration:1200}},
 pounce:{t:'svg',k:()=>[{transform:'translate(0,0) scale(1,1)'},{transform:'translate(0,8px) scale(1.1,.8)',offset:.3},{transform:'translate(-60px,-40px) scale(1,1.05)',offset:.65},{transform:'translate(0,0) scale(1,1)'}],o:{duration:1000,easing:'cubic-bezier(.3,.7,.3,1)'}},
 pounceR:{t:'svg',k:()=>[{transform:'translate(0,0) scale(1,1)'},{transform:'translate(0,8px) scale(1.1,.8)',offset:.3},{transform:'translate(60px,-40px) scale(1,1.05)',offset:.65},{transform:'translate(0,0) scale(1,1)'}],o:{duration:1000,easing:'cubic-bezier(.3,.7,.3,1)'}},
 crouch:{t:'svg',k:()=>[{transform:'scale(1,1)'},{transform:'scale(1.06,.82) translateY(10px)',offset:.4},{transform:'scale(1.06,.82) translateY(10px)',offset:.8},{transform:'scale(1,1)'}],o:{duration:1500}},
 grow:{t:'svg',k:()=>[{transform:'scale(1)'},{transform:'scale(1.3)',offset:.3},{transform:'scale(1.25)',offset:.7},{transform:'scale(1)'}],o:{duration:1200}},
 growBig:{t:'svg',k:()=>[{transform:'scale(1)'},{transform:'scale(1.6)',offset:.4},{transform:'scale(1.55)',offset:.7},{transform:'scale(1)'}],o:{duration:1600}},
 shrink:{t:'svg',k:()=>[{transform:'scale(1)'},{transform:'scale(.5)',offset:.4},{transform:'scale(.5)',offset:.7},{transform:'scale(1)'}],o:{duration:1500}},
 float:{t:'svg',k:()=>[{transform:'translateY(0) rotate(0)'},{transform:'translateY(-40px) rotate(-5deg)',offset:.4},{transform:'translateY(-40px) rotate(5deg)',offset:.7},{transform:'translateY(0) rotate(0)'}],o:{duration:2200,easing:'ease-in-out'}},
 tiptoe:{t:'svg',k:()=>[{transform:'translateX(0) translateY(0)'},{transform:'translateX(-15px) translateY(-6px)'},{transform:'translateX(-30px) translateY(0)'},{transform:'translateX(-45px) translateY(-6px)'},{transform:'translateX(-60px) translateY(0)'},{transform:'translateX(0) translateY(0)'}],o:{duration:1800}},
 bow:{t:'svg',k:()=>[{transform:'rotate(0)'},{transform:'rotate(14deg) translateY(6px)',offset:.35},{transform:'rotate(14deg) translateY(6px)',offset:.7},{transform:'rotate(0)'}],o:{duration:1500}},
 lean:{t:'svg',k:()=>[{transform:'rotate(0)'},{transform:'rotate(-22deg)',offset:.4},{transform:'rotate(-22deg)',offset:.7},{transform:'rotate(0)'}],o:{duration:1600}},
 flex:{t:'arms|body',k:()=>[{transform:'scale(1)'},{transform:'scale(1.25)'},{transform:'scale(1)'}],o:{duration:400,iterations:3}},
 hug:{t:'svg',k:()=>[{transform:'scale(1)'},{transform:'scale(1.15) translateY(10px)',offset:.4},{transform:'scale(1.15) translateY(10px)',offset:.7},{transform:'scale(1)'}],o:{duration:1600}},
 bounce:{t:'svg',k:()=>[{transform:'translateY(0)'},{transform:'translateY(-30px)'},{transform:'translateY(0)'},{transform:'translateY(-18px)'},{transform:'translateY(0)'},{transform:'translateY(-8px)'},{transform:'translateY(0)'}],o:{duration:1200,easing:'ease-out'}},
 tremble:{t:'svg',k:()=>[{transform:'translateX(-2px)'},{transform:'translateX(2px)'}],o:{duration:60,iterations:20,direction:'alternate'}},
 stomp:{t:'pawL',k:()=>[{transform:'translateY(0)'},{transform:'translateY(-14px)'},{transform:'translateY(0)'}],o:{duration:260,iterations:3}},
 sneak:{t:'svg',k:()=>[{transform:'translateX(0) scaleY(1)'},{transform:'translateX(-20px) scaleY(.9)'},{transform:'translateX(-40px) scaleY(1)'},{transform:'translateX(-60px) scaleY(.9)'},{transform:'translateX(-80px) scaleY(1)',offset:.7},{transform:'translateX(0) scaleY(1)'}],o:{duration:2200,easing:'ease-in-out'}},
 lick:{t:'pawR',k:()=>[{transform:'translate(0,0)'},{transform:'translate(-14px,-40px) rotate(-30deg)',offset:.3},{transform:'translate(-14px,-44px) rotate(-30deg)',offset:.5},{transform:'translate(-14px,-40px) rotate(-30deg)',offset:.7},{transform:'translate(0,0)'}],o:{duration:1500}},
 headSpin:{t:'head',k:()=>[{transform:'rotate(0)'},{transform:'rotate(-20deg)'},{transform:'rotate(20deg)'},{transform:'rotate(-12deg)'},{transform:'rotate(12deg)'},{transform:'rotate(0)'}],o:{duration:900}},
};
// dráhy propů (x,y v %); 'top' propy začínají nad scénou
const P={
 across:[[-12,72],[105,72]], acrossBack:[[105,72],[-12,72]], fall:[[50,-12],[50,30]], fallSide:[[20,-12],[20,80]],
 fly:[[-10,20],[30,10],[60,25],[110,8]], flyBack:[[110,15],[60,5],[30,22],[-10,10]], flutter:[[10,60],[30,20],[55,45],[75,15],[90,50]],
 up:[[50,80],[50,-15]], upLeft:[[80,80],[20,-15]], hover:[[50,15],[48,20],[52,15],[50,18]], bounceIn:[[-10,20],[30,70],[50,30],[70,72],[105,40]],
 rise:[[85,90],[85,10]], set:[[15,10],[15,90]], toCat:[[105,30],[62,55]], fromCat:[[50,55],[110,20]], swirl:[[50,45],[70,30],[50,15],[30,30],[50,45]],
 dropLeft:[[25,-10],[25,62]], zig:[[-10,40],[25,20],[50,45],[75,20],[105,45]], orbit:[[50,10],[85,45],[50,80],[15,45],[50,10]],
};
const EGGS100=[
 // ── dny 1–10: kotě ──
 {id:'wink',min:0,say:'😉',m:['wink']},
 {id:'purr',min:0,say:'prrrr…',m:['purr'],fx:{g:['💗','💕'],n:6}},
 {id:'hop',min:0,say:'hop!',m:['jump']},
 {id:'roll',min:0,say:'kotrmelec!',m:['roll']},
 {id:'zzz',min:0,say:'chrrr… pšt',m:['sleep'],fx:{g:['💤'],n:3,top:25}},
 {id:'tail',min:0,say:'švih švih',m:['tail']},
 {id:'stretch',min:0,say:'áááách',m:['stretch']},
 {id:'sneeze',min:0,say:'Hep-ČÍ!',m:['sneeze'],fx:{g:['💦'],n:4,top:40,delay:380}},
 {id:'drop',min:0,say:'Fuj! Mokro!',prop:{g:'💧',path:P.fall,dur:650,size:26},then:['shake'],fx:{g:['💧','💦'],n:7,top:35,delay:700}},
 {id:'butterfly',min:0,say:'motýýýl…',prop:{g:'🦋',path:P.flutter,dur:2200,size:26},m:['follow','bigEyes']},
 // ── 11–20 ──
 {id:'yarn',min:0,say:'klubíčko!!',prop:{g:'🧶',path:P.across,dur:1600,size:30,spin:true},m:['follow'],then:['jump']},
 {id:'wave',min:0,say:'Ahoj! 👋',m:['waveR']},
 {id:'dance',min:0,say:'♪ ♫ ♪',m:['dance'],fx:{g:['🎵','🎶'],n:5,top:20}},
 {id:'peek',min:0,say:'BAF!',m:['peek'],sayDelay:1500},
 {id:'leaf',min:0,say:'padá…',prop:{g:'🍂',path:P.fallSide,dur:2400,size:24,sway:true},m:['lookL','tiltL']},
 {id:'mouse',min:0,say:'MYŠ!',prop:{g:'🐭',path:P.across,dur:1300,size:26},m:['bigEyes'],then:['pounce']},
 {id:'coin',min:0,say:'moje!',prop:{g:'🪙',path:P.fall,dur:800,size:26,spin:true},then:['pawsUp','hop'],fx:{g:['✨'],n:5,top:40,delay:800}},
 {id:'lick',min:0,say:'mňam, tlapka',m:['lick','tiltR']},
 {id:'bird',min:0,say:'ptáček…',prop:{g:'🐦',path:P.fly,dur:2200,size:24},m:['follow','tailFast']},
 {id:'yawn',min:0,say:'áááách… ospalá',m:['headBack'],fx:{g:['💤'],n:2,top:20,delay:900}},
 // ── 21–30 ──
 {id:'sun',min:0,say:'sluníčko ☀️',prop:{g:'☀️',path:P.rise,dur:2000,size:34},m:['stretch'],then:['sleep']},
 {id:'snow',min:0,say:'brrr ❄️',fx:{g:['❄️','❄️','✨'],n:12,top:-5,fall:true},m:['tremble'],then:['shake']},
 {id:'fish',min:0,say:'rybička!',prop:{g:'🐟',path:P.bounceIn,dur:2200,size:26},m:['follow'],then:['pounceR']},
 {id:'balloon',min:0,say:'kam letí?!',prop:{g:'🎈',path:P.up,dur:2600,size:30},m:['headBack','bigEyes']},
 {id:'bee',min:0,say:'bzzz… PRYČ!',prop:{g:'🐝',path:P.orbit,dur:2000,size:22},m:['headSpin'],then:['kick']},
 {id:'shy',min:0,say:'…',m:['pawsUp','tiltL'],fx:{g:['🙈'],n:1,top:30}},
 {id:'bow',min:0,say:'klaním se',m:['bow']},
 {id:'rain',min:0,say:'prší!',fx:{g:['💧','💧'],n:14,top:-5,fall:true},m:['crouch'],then:['shake']},
 {id:'star',min:0,say:'přej si něco ⭐',prop:{g:'⭐',path:P.fly,dur:1400,size:24},m:['bigEyes','lookR'],fx:{g:['✨'],n:6,top:15,delay:1400}},
 {id:'laser',min:1,say:'MÁM TĚ!',prop:{g:'laser',path:P.zig,dur:1600},m:['follow'],then:['pounce']},
 // ── 31–40 ──
 {id:'flip',min:1,say:'tadá!',m:['flip']},
 {id:'moonwalk',min:1,say:'hee hee',m:['moonwalk'],fx:{g:['🎵'],n:3,top:25}},
 {id:'box',min:1,say:'krabice = můj domov',prop:{g:'📦',path:[[50,95],[50,60]],dur:700,size:44},then:['peek']},
 {id:'ufo',min:1,say:'ne ne ne!!',prop:{g:'🛸',path:P.hover,dur:2200,size:40},m:['float'],then:['shake']},
 {id:'pizza',min:1,say:'pizzaaa',prop:{g:'🍕',path:P.toCat,dur:1000,size:30},m:['bigEyes'],then:['hop','purr']},
 {id:'ghost',min:1,say:'d-d-duch?!',prop:{g:'👻',path:P.swirl,dur:2200,size:34},m:['tremble'],then:['bigJump']},
 {id:'apple',min:1,say:'gravitace!',prop:{g:'🍎',path:P.fall,dur:600,size:26},then:['sneeze','tiltL']},
 {id:'music',min:1,say:'můj hit',m:['sway','drum'],fx:{g:['🎶','🎵','🎤'],n:7,top:15}},
 {id:'mirror',min:1,say:'kdo je to?',prop:{g:'🪞',path:[[80,50],[80,50]],dur:1800,size:40},m:['lookR','tiltR'],then:['headShake']},
 {id:'highfive',min:1,say:'plácni si! ✋',m:['waveL','waveR']},
 // ── 41–50 ──
 {id:'kite',min:1,say:'drak letííí',prop:{g:'🪁',path:P.flutter,dur:2600,size:30},m:['follow','tail']},
 {id:'bubbles',min:1,say:'bublinky!',fx:{g:['🫧','🫧','🫧'],n:10,top:60,slow:true},m:['pawsUp'],then:['hop']},
 {id:'hat',min:1,say:'sluší mi?',prop:{g:'🎩',path:[[50,-12],[50,8]],dur:800,size:34,stay:2200},m:['tiltL'],then:['bow']},
 {id:'phone',min:1,say:'nezvedám, jsem kočka',prop:{g:'📱',path:[[20,70],[20,70]],dur:1500,size:28,buzz:true},m:['lookL','headShake']},
 {id:'rocket',min:1,say:'3… 2… 1…',m:['tremble'],then:['bigJump'],fx:{g:['🔥','💨'],n:6,top:80,delay:800}},
 {id:'feather',min:1,say:'hm hm hm',prop:{g:'🪶',path:P.fallSide,dur:2800,size:24,sway:true},m:['follow'],then:['sneeze']},
 {id:'tiptoe',min:1,say:'ššš…',m:['sneak']},
 {id:'cheese',min:1,say:'sýr? pro myš?',prop:{g:'🧀',path:P.acrossBack,dur:1500,size:24},m:['followBack','bigEyes']},
 {id:'bell',min:1,say:'cink cink',prop:{g:'🔔',path:[[50,-10],[50,10]],dur:600,size:30,swing:true},m:['headSpin']},
 {id:'muscles',min:2,say:'💪 síla úroků',m:['flex']},
 // ── 51–60 ──
 {id:'spin',min:2,say:'točím se!',m:['spin']},
 {id:'shadow',min:2,say:'kdo to je?!',prop:{g:'🐈‍⬛',path:P.across,dur:1800,size:34},m:['follow','bigEyes'],then:['shake']},
 {id:'laser2',min:2,say:'…skoro!',prop:{g:'laser',path:P.orbit,dur:1800},m:['follow'],then:['pounceR']},
 {id:'rainbow',min:2,say:'duha! 🌈',prop:{g:'🌈',path:[[50,-15],[50,12]],dur:1200,size:60,stay:1500},m:['headBack','bigEyes']},
 {id:'gift',min:2,say:'pro mě?!',prop:{g:'🎁',path:P.fall,dur:800,size:32,stay:800},then:['bounce'],fx:{g:['✨','🎉'],n:8,top:40,delay:1400}},
 {id:'backflip',min:2,say:'salto!',m:['backflip']},
 {id:'moon',min:2,say:'dobrou… 🌙',prop:{g:'🌙',path:P.rise,dur:2000,size:32},m:['sleep'],fx:{g:['💤'],n:3,top:25,delay:1200}},
 {id:'skate',min:2,say:'ollie!',m:['slideL'],fx:{g:['🛹'],n:1,top:85}},
 {id:'butterfly2',min:2,say:'na nose!',prop:{g:'🦋',path:[[10,60],[35,25],[50,48]],dur:1800,size:24,stay:1200},m:['follow'],then:['sneeze']},
 {id:'ninja',min:2,say:'ninja kočka',m:['sneak'],then:['pounce'],fx:{g:['💨'],n:4,top:70,delay:1800}},
 // ── 61–70 ──
 {id:'thunder',min:2,say:'BUM!',fx:{g:['⚡'],n:3,top:5},m:['tremble'],then:['crouch']},
 {id:'chase',min:2,say:'chyť mě!',m:['slideR'],then:['slideL']},
 {id:'dj',min:2,say:'drop the beat',m:['drum','wiggle'],fx:{g:['🎧','🎵','🔊'],n:6,top:15}},
 {id:'fishjump',min:2,say:'skočila do vody?!',prop:{g:'🐟',path:[[20,90],[50,30],[80,90]],dur:1400,size:28},m:['follow','bigEyes']},
 {id:'money',min:2,say:'létající peníze!',prop:{g:'💸',path:P.fromCat,dur:1500,size:30},m:['bigEyes'],then:['pounceR']},
 {id:'yoga',min:2,say:'námaste 🧘',m:['stretch','lean']},
 {id:'stomp',min:2,say:'dup dup dup',m:['stomp'],fx:{g:['💥'],n:3,top:85}},
 {id:'sunset',min:2,say:'hezký den…',prop:{g:'🌇',path:P.set,dur:2600,size:44},m:['sway']},
 {id:'pounce',min:3,say:'skok šelmy',m:['pounce']},
 {id:'growl',min:3,say:'grrrrr…',m:['grow'],shake:true},
 // ── 71–80 ──
 {id:'hunt',min:3,say:'lov začíná',m:['crouch'],then:['bigJump'],prop:{g:'🐭',path:P.acrossBack,dur:1400,size:26,delay:1400}},
 {id:'tornado',min:3,say:'wooooo',m:['spin','roll'],fx:{g:['🌪️','💨'],n:5,top:30}},
 {id:'tiger',min:3,say:'pruhy jsou in',m:['flex','tailFast'],fx:{g:['🐯'],n:1,top:15}},
 {id:'snowball',min:3,say:'koulovačka!',prop:{g:'⚪',path:P.toCat,dur:700,size:24},then:['shake','pounceR']},
 {id:'meditate',min:3,say:'ommm…',m:['float','sleep'],fx:{g:['✨'],n:6,top:50,slow:true}},
 {id:'trophy',min:3,say:'první místo',prop:{g:'🏆',path:P.fall,dur:900,size:34,stay:1500},then:['pawsUp','bounce']},
 {id:'stealth',min:3,say:'neviděla jsi mě',m:['shrink'],then:['grow']},
 {id:'wind',min:3,say:'fúúú',fx:{g:['🍃','🍂','💨'],n:9,top:40,wind:true},m:['lean','tailFast']},
 {id:'drums',min:3,say:'bubny!',m:['drum'],fx:{g:['🥁','💥'],n:6,top:80}},
 {id:'catnip',min:3,say:'šantaaaa 😵‍💫',prop:{g:'🌿',path:P.toCat,dur:900,size:28},then:['roll','rollBack','dance']},
 // ── 81–90 ──
 {id:'roar',min:4,say:'RAWWWR!',m:['growBig'],shake:true,fx:{g:['💥','⚡'],n:5,top:30}},
 {id:'hug',min:4,say:'obejmutí od lvice',m:['hug'],fx:{g:['❤️','🧡'],n:8}},
 {id:'crownfix',min:4,say:'korunka sedí?',m:['pawsUp','tiltL','tiltR']},
 {id:'lionjump',min:4,say:'lví skok',m:['bigJump'],fx:{g:['💨'],n:4,top:85,delay:200}},
 {id:'savanna',min:4,say:'domov…',prop:{g:'🌅',path:P.rise,dur:2400,size:44},m:['sway','headBack']},
 {id:'kingbow',min:4,say:'poklona královně',m:['bow','bow']},
 {id:'shadowbox',min:4,say:'jab, jab, hák',m:['drum','wiggle'],fx:{g:['🥊'],n:2,top:50}},
 {id:'thunderroar',min:4,say:'BUM! …to jsem byla já',fx:{g:['⚡','💥'],n:6,top:10},m:['growBig']},
 {id:'zoomies',min:4,say:'ZOOMIES!!',m:['slideL','slideR','spin']},
 {id:'proud',min:4,say:'koukej, jak jsem vyrostla',m:['grow','tailCurl']},
 // ── 91–100 ──
 {id:'fireworks',min:4,say:'ohňostroj!',fx:{g:['🎆','🎇','✨'],n:12,top:10},m:['headBack','bigEyes']},
 {id:'crownjump',min:4,say:'korunka drží!',m:['backflip'],fx:{g:['👑'],n:1,top:5}},
 {id:'stars',min:4,say:'hvězdy pro tebe',fx:{g:['⭐','🌟','✨'],n:14,top:-5,fall:true},m:['float']},
 {id:'confetti',min:4,say:'skoro tam!',fx:{g:['🎊','🎉'],n:12,top:0,fall:true},m:['bounce']},
 {id:'medal',min:4,say:'medaile!',prop:{g:'🏅',path:P.fall,dur:900,size:34,stay:1800},then:['pawsUp','purr']},
 {id:'lionroar2',min:5,say:'RAAAWR — a teď potichu',m:['growBig'],shake:true,then:['sleep']},
 {id:'catwalk',min:5,say:'přehlídka',m:['slideR','flip','slideL']},
 {id:'kingsit',min:5,say:'trůn je můj',prop:{g:'🪑',path:[[50,95],[50,75]],dur:600,size:44},then:['bow','purr']},
 {id:'dance100',min:5,say:'tanec vítězů',m:['dance','spin','bounce'],fx:{g:['🎵','🎶','⭐'],n:10,top:15}},
 {id:'finale',min:5,say:'Sto dní. Děkuju, Terez. ❤️',m:['hug','growBig'],fx:{g:['❤️','⭐','🎉','👑'],n:20,top:10}},
];
